### PR TITLE
Conversion to base elements for extension field elements

### PR DESCRIPTION
**Pull request by irakliyk**
This PR adds convenience methods to convert quadratic and cubic extension field elements into corresponding arrays of base field elements.

### CODE REVIEW

**Comment by irakliyk** [comment]
@Al-Kindi-0, @Nashtare - would appreciate a review. Thank you!

**Comment by Nashtare** [comment]
LGTM. Perhaps we want to emphasize the array ordering? (I assume it's relatively straightforward though)

**Review by Al-Kindi-0 — COMMENTED** [review]
LGTM as well!

**Comment by irakliyk** [comment]
Thank @Nashtare, @Al-Kindi-0!

> Perhaps we want to emphasize the array ordering?

Added a short sentence for this in the comments.

**Pull request merged**
