### PR TITLE
Remove conjugate term in deep composition polynomial

### PR DESCRIPTION
**Pull request by Al-Kindi-0**
Following the remark [here](https://twitter.com/EliBenSasson/status/1625140730736828416) the present PR proposes a simplification in the way the deep composition polynomial is computed.

### CODE REVIEW

**Review by irakliyk — CHANGES_REQUESTED** [review]
Looks good! Thank you! Two small comments:

1. Do we still need `RandomCoin::draw_triple()` method? If not, we could probably remove it.
2. Could you add a bullet point to the CHANGELOG describing the change? (this could probably go under v0.6 heading).

**Comment by Al-Kindi-0** [comment]
Thank you!

1. You are right, it was useful only in the context of conjugate term. I have removed it.
2. Sure will do that.

**Review by irakliyk — APPROVED** [review]
Looks good! Thank you!

@Nashtare - curious if you have any comments.

**Comment by Nashtare** [comment]
I had a look yesterday and it seemed good to me, modulo the same comment you had (if nothing changed in the meantime!).

**Pull request merged**
